/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdcc4",
        "on-surface-variant": "#55423d",
        "inverse-surface": "#31302d",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#efbc98",
        "primary-fixed": "#ffdbd0",
        "on-secondary-fixed-variant": "#334d31",
        "surface-bright": "#fdf9f4",
        "inverse-primary": "#ffb59f",
        "surface-container-highest": "#e6e2dd",
        "on-surface": "#1c1c19",
        "on-secondary-fixed": "#072009",
        "outline-variant": "#dcc1b9",
        "error-container": "#ffdad6",
        primary: "#6f240a",
        tertiary: "#56361b",
        "surface-tint": "#9b4428",
        error: "#ba1a1a",
        "surface-container-high": "#ebe8e3",
        secondary: "#4a6548",
        "secondary-container": "#c9e8c3",
        "on-secondary-container": "#4e694c",
        "on-primary-container": "#ffb8a3",
        "on-tertiary-fixed": "#2f1501",
        "on-tertiary-fixed-variant": "#613f24",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#89726c",
        "surface-dim": "#ddd9d5",
        "secondary-fixed-dim": "#b0cfab",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb59f",
        background: "#fdf9f4",
        "secondary-fixed": "#ccebc6",
        "on-primary-fixed": "#3a0a00",
        "inverse-on-surface": "#f4f0eb",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f1bf9b",
        "tertiary-container": "#714c30",
        "surface-container": "#f1ede8",
        surface: "#fdf9f4",
        "on-background": "#1c1c19",
        "on-secondary": "#ffffff",
        "primary-container": "#8e3a1f",
        "surface-variant": "#e6e2dd",
        "surface-container-low": "#f7f3ee",
        "on-primary-fixed-variant": "#7c2d13",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        gutter: "24px",
      },
      fontFamily: {
        "display-lg": ["Noto Serif"],
        "label-sm": ["Be Vietnam Pro"],
        "body-md": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "headline-md": ["Noto Serif"],
        "headline-lg": ["Noto Serif"],
      },
      fontSize: {
        "display-lg": ["4.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["0.875rem", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["2rem", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["3rem", { lineHeight: "1.2", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};